##################################################
# DO Community Playbooks: Apache on Ubuntu 18.04
##################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
        
    - name: Create document root1
      file:
        path: "/var/www/{{ http_host }}/css"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
      
    - name: Create document root2
      file:
        path: "/var/www/{{ http_host }}/js"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
      
    - name:  Create document root3
      file:
        path: "/var/www/{{ http_host }}/css"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
        
    - name: Create document root4
      file:
        path: "/var/www/{{ http_host }}/images"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
        
    - name: Copy the temp directory recursively to destination directory
      copy:
        src: "files/"
        dest: "/var/www/{{ http_host }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        force: "yes"
        mode: 0755

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
        
    - name: a2ensite {{ http_conf }}
      command: a2ensite {{ http_conf }}
      args:
        creates: /etc/apache2/sites-enabled/{{ http_conf }}.conf
    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify:
        - restart apache2
      
    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify:
        - restart apache2

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 8081
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:{{ http_port }}>" state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    #- name: Disable default Apache site
      # shell: /usr/sbin/a2dissite 000-default.conf
      # # when: disable_default
      # notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

 
